fn=input("Enter your First Name : ")
ln=input("Enter your Last Name : ")
ct=input("Enter your City : ")
co=input("Enter your Course : ")
ag=input("Enter your Age : ")
print(" ")
print(" ")
funm=fn+" "+ln
print(f"Full Name in Title Case :\n    {funm.title()}")
print(" ")
print(f"Full Name in Lower Case :\n    {funm.lower()}")
print(" ")
print(f"Full Name in Upper Case :\n    {funm.upper()}")
print(" ")
print(f"Full Name Length is :\n    {len(funm)}")
print(" ")
print(f"First Character in Full Name is :\n    {funm[0]}")
print(" ")
print(f"Last Character in Full Name is :\n    {funm[-1]}")
print(" ")
print(f"Youe City is :\n    {ct.upper()}\n    And Course is :\n        {co.title()}")
print(" ")
print(f"Youe Age is :\n    {ag}")
print(" ")
print(f"Is you Coures is Python :\n    {"python" in co.lower()}")
print(" ")
b=input("Enter Word to replace first word of Course : ")
print(" ")
print(f"Replaced {co.split()[0]} from this {b} is :\n    {co.replace(co.split()[0],b)}")
print(" ")
print(f"Number of Word in Course Name is :\n    {len(co.split())}")