x=input("Enter Your Full Name :")
x=x.strip()
print(f"Cleaned Name is : {x}")
print(f"Name in uppercase : {x.upper()}")
print(f"Name in lowercase : {x.lower()}")
print(f"Name in titlecase : {x.title()}")
print(f"Length of Name is : {len(x)}")
print(f"First character : {x[0]}")
print(f"Last character : {x[-1]}")
print(f"Does name contain letter 'a' in it :- {"a" in x.lower()}")