a=input("Enter a sentence : ")
print("")
print(f"Original Sentence :- \n {a}")
print("")
print(f"Number of character :- \n {len(a)}")
print("")
print(f"Number of words :- \n {len(a.split())}")
print("")
print(f"First Character in sentence :- \n {a.split()[0][0]}")
print("")
print(f"Last Character in sentence :- \n {a.split()[-1][-1]}")
print("")
print(f"Sentence in Lower Case :- \n {a.lower()}")
print("")
print(f"Sentence in Upper Case :- \n {a.upper()}")
print("")
print(f"Sentence in Title Case :- \n {a.title()}")
print("")
print(f"Whether Python Exist in this sentence :- \n {"python" in a.lower()}")
print("")
b=input("Enter any character to find it's occurence in given sentence by you : ")
print("")
print(f"Occurence of {b} in your Given Sentence is :- \n {a.lower().count(b.lower())}")